name: _scorecard

on:
  workflow_call:
    inputs:
      publish-results:
        description: Publish results of Scorecard analysis
        type: boolean
        required: false
        default: true

permissions:
  id-token: none
  security-events: none

jobs:
  scorecard:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        security-events: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
      - name: ✅ run scorecard analysis
        uses: ossf/scorecard-action@0864cf19026789058feabb7e87baa5f140aac736 # v2.3.1
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_TOKEN }}
          publish_results: ${{ inputs.publish-results }}
      - name: ⏫ upload sarif artifact
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.2
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      - name: 📦 upload sarif results
        uses: github/codeql-action/upload-sarif@c7f9125735019aa87cfc361530512d50ea439c71 # v3.25.1
        with:
          sarif_file: results.sarif
