name: clean-owners

on:
  # Scheduled trigger
  schedule:
    # Run weekly on Saturdays
    - cron: "30 1 * * 6"
  # Manual trigger
  workflow_dispatch:

permissions:
  issues: none

jobs:
  clean-owners:
    runs-on: ubuntu-latest
    permissions:
        issues: write
    steps:
      - name: 🧼 clean codeowners
        uses: github/cleanowners@696df8ed6b2f730f5440df3f80fcf9aa6bb51ea1 # no semver release yet
        env:
          GH_TOKEN: ${{ secrets.CISCO_SERVICE_TOKEN }}
          ORGANIZATION: cisco-ospo
          EXEMPT_REPOS: "cisco-ospo/.github, cisco-ospo/.allstar"
          DRY_RUN: true
