name: dry-run

on:
  pull_request_review:
    types: [submitted]
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches-ignore: [main]
    paths: [org/**]
    

jobs:
  lint-yaml:
    if: github.event.review.state == 'approved' && github.repository.owner != 'openclarity'
    uses: ./.github/workflows/_lint.yml
  dry-run:
    if: github.event.review.state == 'approved' && github.repository.owner != 'openclarity'
    uses: ./.github/workflows/_sync.yml
    permissions: read-all
    secrets: inherit
    with:
      confirm: false
