name: scorecard-test

on:
  workflow_call:
    inputs:
      publish-results:
        description: Publish results of Scorecard analysis
        type: boolean
        required: false
        default: true

permissions:
  id-token: none
  security-events: none

jobs:
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      security-events: write
    steps:
      - uses: actions/create-github-app-token@f2acddfb5195534d487896a656232b016a682f3c # v1.9.0
        id: app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
      - name: ✅ run scorecard analysis
        uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46 # v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ steps.app-token.outputs.token }}
          publish_results: ${{ inputs.publish-results }}
      - name: ⏫ upload sarif artifact
        uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4.3.5
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      - name: 📦 upload sarif results
        uses: github/codeql-action/upload-sarif@afb54ba388a7dca6ecae48f608c4ff05ff4cc77a # v3.25.15
        with:
          sarif_file: results.sarif
