name: "OpenSSF Scorecard reporting"
on: 
  # Scheduled trigger
  schedule:
    # Run every Sunday at 00:00
    - cron: "0 0 * * 0"
  # Manual trigger
  workflow_dispatch:

permissions:
  # Write access in order to update the local files with the reports
  contents: write
  pull-requests: none 
  # Write access in order to create issues
  issues: write
  packages: none

jobs:
  security-scoring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: OpenSSF Scorecard Monitor
        uses: UlisesGascon/openssf-scorecard-monitor@v2.0.0-beta6
        id: openssf-scorecard-monitor
        with:
          scope: reports/scorecard/scope.json
          database: reports/scorecard/database.json
          report: reports/scorecard/report.md
          auto-commit: false
          auto-push: false
          generate-issue: true
          # The token is needed to create issues, discovery mode and pushing changes in files
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discovery-enabled: true
          discovery-orgs: 'cisco,cisco-open,cisco-ospo'
      - name: Print the scores
        run: |
          echo '${{ steps.openssf-scorecard-monitor.outputs.scores }}'
      - name: Create pull request
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54 # v4.2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: OpenSSF Scorecard Report Updated
          title: OpenSSF Scorecard Report Updated
          body: OpenSSF Scorecard Report Updated
          base: main
          assignees: ${{ github.actor }}
          branch: openssf-scorecard-report-updated
          delete-branch: true
