name: scorecard-test

on:
  workflow_call:
    inputs:
      publish-results:
        description: Publish results of Scorecard analysis
        type: boolean
        required: false
        default: true

permissions:
  id-token: none
  security-events: none

jobs:
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      security-events: write
    steps:
      - uses: actions/create-github-app-token@dff4b11d10ecc84d937fdd0653d8343a88c5b9c4 # v1.9.0
        id: app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
      - name: ✅ run scorecard analysis
        uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46 # v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ steps.app-token.outputs.token }}
          publish_results: ${{ inputs.publish-results }}
      - name: ⏫ upload sarif artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      - name: 📦 upload sarif results
        uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f # v3.28.18
        with:
          sarif_file: results.sarif
